### ISSUE TITLE
[Documentation]Usage

### ISSUE THREAD

**Issue by tugbakara** [ZhenshengLee/perception_cuda_pcl#9]
Hi @ZhenshengLee , thanks for awesome contribution! :)
In the instruction I couldn't find it how to use it, is it usable with lidars, cams (realsense series) etc.. If it is, how?
Could you add more details about it in main page of the package, please?

**Comment by ZhenshengLee** [comment]
@tugbakara  thanks for your report!
This repo is like https://github.com/ros-perception/perception_pcl 
You can refer to the following materials 
- the unit test https://github.com/ZhenshengLee/perception_cuda_pcl/blob/master/cuda_pcl_conversions/test/cuda_pcl_conversions/test_cuda_pcl_conversions.cpp
- the example https://github.com/ZhenshengLee/perception_cuda_pcl/blob/master/cuda_pcl_conversions/tool/cuda_pcl_conversions_test_node.cpp
- the bigger example to show the performance of downsampler of pointcloud https://github.com/ZhenshengLee/ga_points_downsampler

**Comment by tugbakara** [comment]
Thanks @ZhenshengLee ! I will try to use this package if there is any error, issue I'll provide here, I hope you will be available to discuss :)

**Comment by ZhenshengLee** [comment]
OK, and there are known bugs in this repo... I'll try to find sometime to fix this.
